version: '3'

services:
  api:
    image: rust:1.77-alpine3.19
    links:
      - db
      - redis
    volumes:
      - ../back/target/debug/:/var/www/api

  api_nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./server:/var/www
      - ./data/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx/logs:/var/log/nginx
    depends_on:
      - laravel

    front:

  db:
    image: postgres:16.2-alpine3.18
    restart: always
    shm_size: 128mb
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD_FILE: /tmp/pp.p
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: xivif
      MYSQL_USER: xivif
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      # postgres db永続化 / eternalize to postgress store
      - ./db/var/lib/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata
      # postgres 設定ファイル配置
      - ./db/tmp/pp.p:/tmp/pp.p
    ports:
      - 25432:5432

  redis:
    image: redis:7.0.11
    ports:
      - 6379:6379
    volumes:
      - ./data/redis/data:/data
