apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: rust:slim-bookworm
        ports:
        - containerPort: 4126
        env:
        - name: POSTGRES_HOST
          value: postgresql
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: your_database_name
        - name: POSTGRES_USER
          value: your_database_user
        - name: POSTGRES_PASSWORD
          value: your_database_password
      - name: backend
        image: nginx:stable-alpine3.17
        ports:
        - containerPort: 80
